#pragma once
#include <glm/glm.hpp>

enum CARD_ID
{
	CARD_ID_RED_0, CARD_ID_RED_1, CARD_ID_RED_2, CARD_ID_RED_3, CARD_ID_RED_4, CARD_ID_RED_5, CARD_ID_RED_6,
	CARD_ID_RED_7, CARD_ID_RED_8, CARD_ID_RED_9, CARD_ID_RED_PAUSE, CARD_ID_RED_SWAP, CARD_ID_RED_ADD,
	CARD_ID_CHOOSE_COLOR,
	CARD_ID_YELLOW_0, CARD_ID_YELLOW_1, CARD_ID_YELLOW_2, CARD_ID_YELLOW_3, CARD_ID_YELLOW_4, CARD_ID_YELLOW_5, CARD_ID_YELLOW_6,
	CARD_ID_YELLOW_7, CARD_ID_YELLOW_8, CARD_ID_YELLOW_9, CARD_ID_YELLOW_PAUSE, CARD_ID_YELLOW_SWAP, CARD_ID_YELLOW_ADD,
	CARD_ID_ADD_4,
	CARD_ID_GREEN_0, CARD_ID_GREEN_1, CARD_ID_GREEN_2, CARD_ID_GREEN_3, CARD_ID_GREEN_4, CARD_ID_GREEN_5, CARD_ID_GREEN_6,
	CARD_ID_GREEN_7, CARD_ID_GREEN_8, CARD_ID_GREEN_9, CARD_ID_GREEN_PAUSE, CARD_ID_GREEN_SWAP, CARD_ID_GREEN_ADD,
	
	CARD_ID_BLANK,

	CARD_ID_BLUE_0, CARD_ID_BLUE_1, CARD_ID_BLUE_2, CARD_ID_BLUE_3, CARD_ID_BLUE_4, CARD_ID_BLUE_5, CARD_ID_BLUE_6,
	CARD_ID_BLUE_7, CARD_ID_BLUE_8, CARD_ID_BLUE_9, CARD_ID_BLUE_PAUSE, CARD_ID_BLUE_SWAP, CARD_ID_BLUE_ADD,

	CARD_ID_BLANK2,

};


void InitializeCardPipeline(void* assetManager);

void AddCard(CARD_ID back, CARD_ID front, const glm::mat4& transform);
void ClearCards();

void DrawCards(const glm::mat4& proj, const glm::mat4& view);

bool HitTest(const glm::mat4& model, const glm::vec3& camPos, const glm::vec3& mouseRay);